Add rclone setup

diff --git a/.github/workflows/packages_reset.yaml b/.github/workflows/packages_reset.yaml
--- a/.github/workflows/packages_reset.yaml
+++ b/.github/workflows/packages_reset.yaml
@@ -81,6 +81,24 @@ jobs:
           platforms: ${{ steps.variables.outputs.platform }}
         if: steps.variables.outcome=='success'
 
+      - name: Install rclone & add rclone conf file
+        uses: nick-fields/retry@v2
+        env:
+            RCLONE_CONF: ${{secrets.RCLONE_CONF}}
+        with:
+          timeout_minutes: 20
+          max_attempts: 10
+          shell: bash
+          command: |
+            set -xe
+            sudo -v ; curl https://rclone.org/install.sh | sudo bash || true
+            echo "$RCLONE_CONF" > ~/.rclone.conf
+            if ! command -v rclone &> /dev/null
+            then
+                echo "rclone could not be found"
+                exit 1;
+            fi
+
       - run: |
           rclone copyto js2:/gha-build/$(cat containername)/$(cat arch)/$(cat runstarttime)/binaries/src/contrib js2:/${{steps.variables.outputs.biocver}}/container-binaries/$(cat containername)/$(cat arch)/binaries/src/contrib -vvvvvv
         if: steps.variables.outcome=='success'
